// Generated by tools/digitgrid.py --emit-c. Do not edit: redraw the
// glyphs in that file and run it again.
#pragma once
#include <pebble.h>

#define DIGIT_W 10
#define DIGIT_H 13
#define DIGIT_COLON 10
// The colon inks only these columns, so the one-line layout can give it
// a slot of its own rather than a full digit width.
#define DIGIT_COLON_L 4
#define DIGIT_COLON_R 6
// ...and these are the columns the digits ink. A drawing with a blank
// column down one side is centered by its ink, not by its box, or the
// blank counts as part of the glyph and pushes the whole clock over.
#define DIGIT_INK_L 1
#define DIGIT_INK_R 9

// One bitmask per row, bit (DIGIT_W-1) is the leftmost column.
extern const uint16_t DIGIT_ROWS[11][DIGIT_H];

// Every set pixel as a `scale` x `scale` box, top-left at (x, top),
// in the context fill color. Runs are one rectangle, not one per pixel.
void digit_draw(GContext *ctx, int idx, int x, int top, int scale);
